export type SVOItem = {
  id: string;
  subject: string;
  verb: string;
  object: string;
  correct: string;
};

export const sentenceShuffleData: SVOItem[] = [
  {
    id: "1",
    subject: "The child",
    verb: "kicks",
    object: "the ball",
    correct: "The child kicks the ball",
  },
  {
    id: "2",
    subject: "The girl",
    verb: "reads",
    object: "a book",
    correct: "The girl reads a book",
  },
  {
    id: "3",
    subject: "The dog",
    verb: "chases",
    object: "the cat",
    correct: "The dog chases the cat",
  },
  {
    id: "4",
    subject: "The teacher",
    verb: "explains",
    object: "the lesson",
    correct: "The teacher explains the lesson",
  },
  {
    id: "5",
    subject: "The baby",
    verb: "drinks",
    object: "milk",
    correct: "The baby drinks milk",
  },
  {
    id: "6",
    subject: "The student",
    verb: "eats",
    object: "an apple",
    correct: "The student eats an apple",
  },
  {
    id: "7",
    subject: "The girl",
    verb: "draws",
    object: "a picture",
    correct: "The girl draws a picture",
  },
  {
    id: "8",
    subject: "The cat",
    verb: "likes",
    object: "fish",
    correct: "The cat likes fish",
  },
  {
    id: "9",
    subject: "The bird",
    verb: "builds",
    object: "a nest",
    correct: "The bird builds a nest",
  },
  {
    id: "10",
    subject: "The player",
    verb: "throws",
    object: "the toy",
    correct: "The player throws the toy",
  },

  {
    id: "11",
    subject: "The girl",
    verb: "writes",
    object: "a letter",
    correct: "The girl writes a letter",
  },
  {
    id: "12",
    subject: "The kid",
    verb: "opens",
    object: "the door",
    correct: "The kid opens the door",
  },
  {
    id: "13",
    subject: "The dog",
    verb: "carries",
    object: "a stick",
    correct: "The dog carries a stick",
  },
  {
    id: "14",
    subject: "The teacher",
    verb: "checks",
    object: "the work",
    correct: "The teacher checks the work",
  },
  {
    id: "15",
    subject: "The girl",
    verb: "cleans",
    object: "the room",
    correct: "The girl cleans the room",
  },
  {
    id: "16",
    subject: "The child",
    verb: "washes",
    object: "the hands",
    correct: "The child washes the hands",
  },
  {
    id: "17",
    subject: "The cat",
    verb: "climbs",
    object: "the tree",
    correct: "The cat climbs the tree",
  },
  {
    id: "18",
    subject: "The bird",
    verb: "sings",
    object: "a song",
    correct: "The bird sings a song",
  },
  {
    id: "19",
    subject: "The rider",
    verb: "rides",
    object: "a bike",
    correct: "The rider rides a bike",
  },
  {
    id: "20",
    subject: "The girl",
    verb: "feeds",
    object: "the dog",
    correct: "The girl feeds the dog",
  },

  {
    id: "21",
    subject: "The student",
    verb: "finds",
    object: "a coin",
    correct: "The student finds a coin",
  },
  {
    id: "22",
    subject: "The girl",
    verb: "helps",
    object: "the mother",
    correct: "The girl helps the mother",
  },
  {
    id: "23",
    subject: "The dog",
    verb: "guards",
    object: "the house",
    correct: "The dog guards the house",
  },
  {
    id: "24",
    subject: "The teacher",
    verb: "asks",
    object: "a question",
    correct: "The teacher asks a question",
  },
  {
    id: "25",
    subject: "The kid",
    verb: "fixes",
    object: "the toy",
    correct: "The kid fixes the toy",
  },
  {
    id: "26",
    subject: "The girl",
    verb: "answers",
    object: "the question",
    correct: "The girl answers the question",
  },
  {
    id: "27",
    subject: "The cat",
    verb: "catches",
    object: "a mouse",
    correct: "The cat catches a mouse",
  },
  {
    id: "28",
    subject: "The worker",
    verb: "pushes",
    object: "the cart",
    correct: "The worker pushes the cart",
  },
  {
    id: "29",
    subject: "The girl",
    verb: "carries",
    object: "a bag",
    correct: "The girl carries a bag",
  },
  {
    id: "30",
    subject: "The bird",
    verb: "flies",
    object: "over the tree",
    correct: "The bird flies over the tree",
  },

  {
    id: "31",
    subject: "The reader",
    verb: "reads",
    object: "a story",
    correct: "The reader reads a story",
  },
  {
    id: "32",
    subject: "The girl",
    verb: "draws",
    object: "a house",
    correct: "The girl draws a house",
  },
  {
    id: "33",
    subject: "The dog",
    verb: "runs",
    object: "after the ball",
    correct: "The dog runs after the ball",
  },
  {
    id: "34",
    subject: "The teacher",
    verb: "gives",
    object: "homework",
    correct: "The teacher gives homework",
  },
  {
    id: "35",
    subject: "The child",
    verb: "calls",
    object: "the friend",
    correct: "The child calls the friend",
  },
  {
    id: "36",
    subject: "The girl",
    verb: "opens",
    object: "the bag",
    correct: "The girl opens the bag",
  },
  {
    id: "37",
    subject: "The cat",
    verb: "sleeps",
    object: "on the chair",
    correct: "The cat sleeps on the chair",
  },
  {
    id: "38",
    subject: "The bird",
    verb: "eats",
    object: "some seeds",
    correct: "The bird eats some seeds",
  },
  {
    id: "39",
    subject: "The student",
    verb: "writes",
    object: "the name",
    correct: "The student writes the name",
  },
  {
    id: "40",
    subject: "The girl",
    verb: "closes",
    object: "the window",
    correct: "The girl closes the window",
  },

  {
    id: "41",
    subject: "The gardener",
    verb: "plants",
    object: "a tree",
    correct: "The gardener plants a tree",
  },
  {
    id: "42",
    subject: "The girl",
    verb: "waters",
    object: "the plants",
    correct: "The girl waters the plants",
  },
  {
    id: "43",
    subject: "The dog",
    verb: "barks",
    object: "at the stranger",
    correct: "The dog barks at the stranger",
  },
  {
    id: "44",
    subject: "The teacher",
    verb: "reads",
    object: "a story",
    correct: "The teacher reads a story",
  },
  {
    id: "45",
    subject: "The builder",
    verb: "builds",
    object: "a tower",
    correct: "The builder builds a tower",
  },
  {
    id: "46",
    subject: "The girl",
    verb: "cuts",
    object: "the paper",
    correct: "The girl cuts the paper",
  },
  {
    id: "47",
    subject: "The cat",
    verb: "jumps",
    object: "over the box",
    correct: "The cat jumps over the box",
  },
  {
    id: "48",
    subject: "The bird",
    verb: "looks",
    object: "for food",
    correct: "The bird looks for food",
  },
  {
    id: "49",
    subject: "The child",
    verb: "holds",
    object: "the umbrella",
    correct: "The child holds the umbrella",
  },
  {
    id: "50",
    subject: "The girl",
    verb: "wears",
    object: "a hat",
    correct: "The girl wears a hat",
  },
];
