import { ReadingPage } from "./emergingContent"; // adjust path if needed

export const developingContent: ReadingPage[] = [
  {
    id: "dev_1",
    text: "The crow picked some stones.",
    image: null,
    question: "What did the crow pick?",
    options: ["Leaves", "Stones", "Water"],
    answer: "Stones",
  },
  {
    id: "dev_2",
    text: "Ted gets a big net.",
    image: null,
    question: "What does Ted get?",
    options: ["A big net", "A small bag", "A red hat"],
    answer: "A big net",
  },
  {
    id: "dev_3",
    text: "Dad sips water from a mug.",
    image: null,
    question: "Where does Dad sip water from?",
    options: ["From a glass", "From a mug", "From a bottle"],
    answer: "From a mug",
  },
  {
    id: "dev_4",
    text: "The boy planted a carrot seed.",
    image: null,
    question: "What did the boy plant?",
    options: ["A flower", "A carrot seed", "A tree"],
    answer: "A carrot seed",
  },
  {
    id: "dev_5",
    text: "The ant carried a grain of corn.",
    image: null,
    question: "What did the ant carry?",
    options: ["A leaf", "A grain of corn", "A stone"],
    answer: "A grain of corn",
  },
  {
    id: "dev_6",
    text: "Sid and Ana are watching TV.",
    image: null,
    question: "Who is watching TV?",
    options: ["Sid and Ana", "Mom and Dad", "The teacher"],
    answer: "Sid and Ana",
  },
  {
    id: "dev_7",
    text: "The man is crossing the road.",
    image: null,
    question: "Who is crossing the road?",
    options: ["The boy", "The man", "The dog"],
    answer: "The man",
  },
  {
    id: "dev_8",
    text: "Birds build nests.",
    image: null,
    question: "Who builds nests?",
    options: ["Cats", "Birds", "Dogs"],
    answer: "Birds",
  },
  {
    id: "dev_9",
    text: "Mom cooks the meal.",
    image: null,
    question: "Who cooks the meal?",
    options: ["Dad", "Mom", "The child"],
    answer: "Mom",
  },
  {
    id: "dev_10",
    text: "Alex kicks the ball.",
    image: null,
    question: "What does Alex kick?",
    options: ["The ball", "The box", "The chair"],
    answer: "The ball",
  },
  {
    id: "dev_11",
    text: "It is a gray bunny.",
    image: null,
    question: "What color is the bunny?",
    options: ["White", "Gray", "Brown"],
    answer: "Gray",
  },
  {
    id: "dev_12",
    text: "Crabs have hard shells.",
    image: null,
    question: "What do crabs have?",
    options: ["Soft skin", "Hard shells", "Long tails"],
    answer: "Hard shells",
  },
  {
    id: "dev_13",
    text: "I wash and iron my dress.",
    image: null,
    question: "What do I wash and iron?",
    options: ["My shirt", "My dress", "My bag"],
    answer: "My dress",
  },
  {
    id: "dev_14",
    text: "The dog has a collar.",
    image: null,
    question: "What does the dog have?",
    options: ["A collar", "A hat", "A toy"],
    answer: "A collar",
  },
  {
    id: "dev_15",
    text: "The cat jumps on the mat.",
    image: null,
    question: "Where does the cat jump?",
    options: ["On the bed", "On the mat", "On the table"],
    answer: "On the mat",
  },
  {
    id: "dev_16",
    text: "I hug my mom with love.",
    image: null,
    question: "Who do I hug?",
    options: ["My dad", "My mom", "My friend"],
    answer: "My mom",
  },
  {
    id: "dev_17",
    text: "The animals felt hot.",
    image: null,
    question: "How did the animals feel?",
    options: ["Cold", "Hot", "Happy"],
    answer: "Hot",
  },
  {
    id: "dev_18",
    text: "The rug is so dusty.",
    image: null,
    question: "What is dusty?",
    options: ["The rug", "The wall", "The chair"],
    answer: "The rug",
  },
  {
    id: "dev_19",
    text: "She loves to read in the library.",
    image: null,
    question: "Where does she read?",
    options: ["At home", "In the library", "At school"],
    answer: "In the library",
  },
  {
    id: "dev_20",
    text: "I read books to learn many things.",
    image: null,
    question: "Why do I read books?",
    options: ["To sleep", "To learn many things", "To play"],
    answer: "To learn many things",
  },
];
