export const wordImages = {
  apple: require("@/assets/images/words/apple.webp"),
  ball: require("@/assets/images/words/ball.webp"),
  cat: require("@/assets/images/words/cat.webp"),
  dog: require("@/assets/images/words/dog.webp"),
  egg: require("@/assets/images/words/egg.webp"),
  fish: require("@/assets/images/words/fish.webp"),
  goat: require("@/assets/images/words/goat.webp"),
  hat: require("@/assets/images/words/hat.webp"),
  ice: require("@/assets/images/words/ice.webp"),
  jam: require("@/assets/images/words/jam.webp"),
  kite: require("@/assets/images/words/kite.webp"),
  leaf: require("@/assets/images/words/leaf.webp"),
  mat: require("@/assets/images/words/mat.webp"),
  nest: require("@/assets/images/words/nest.webp"),
  owl: require("@/assets/images/words/owl.webp"),
  pig: require("@/assets/images/words/pig.webp"),
  queen: require("@/assets/images/words/queen.webp"),
  rat: require("@/assets/images/words/rat.webp"),
  sun: require("@/assets/images/words/sun.webp"),
  top: require("@/assets/images/words/top.webp"),
  unicorn: require("@/assets/images/words/unicorn.webp"),
  van: require("@/assets/images/words/van.webp"),
  wig: require("@/assets/images/words/wig.webp"),
  xray: require("@/assets/images/words/xray.webp"),
  yoyo: require("@/assets/images/words/yoyo.webp"),
  zebra: require("@/assets/images/words/zebra.webp"),
} as const;
